import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.automationexercise.com/');
  await page.getByRole('link', { name: ' Products' }).click();
  await page.frameLocator('iframe[name="aswift_6"]').getByLabel('Close ad').click();
  await page.locator('.productinfo > .btn').first().click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.locator('div:nth-child(4) > .product-image-wrapper > .single-products > .product-overlay > .overlay-content > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.locator('div:nth-child(5) > .product-image-wrapper > .single-products > .productinfo > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await expect(page.getByText('Rs. 500').first()).toBeVisible();
  await page.getByText('Rs. 400').first().click();
  await expect(page.getByText('Rs. 400').first()).toBeVisible();
  await page.getByText('Rs. 1000').first().click();
  await page.getByRole('row', { name: 'Product Image Blue Top Women' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Product Image Men Tshirt Men' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Product Image Sleeveless' }).getByRole('button').click();
  await page.getByText('Rs. 500').nth(1).click();
  await page.getByText('Rs. 400').nth(1).click();
  await page.getByText('Rs. 1000').nth(1).click();
  await expect(page.getByRole('row', { name: 'Product Image Blue Top Women' }).getByRole('button')).toBeVisible();
  await page.getByRole('row', { name: 'Product Image Men Tshirt Men' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Product Image Sleeveless' }).getByRole('button').click();
  await page.getByText('Rs. 500').nth(1).click();
  await page.getByText('Rs. 400').nth(1).click();
  await page.getByText('Rs. 1000').nth(1).click();
  await expect(page.getByText('Rs. 500').nth(1)).toBeVisible();
  await page.getByText('Rs. 400').nth(1).click();
  await expect(page.getByText('Rs. 400').nth(1)).toBeVisible();
  await expect(page.getByText('Rs. 1000').nth(1)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Rs. 500' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Rs. 400' }).first()).toBeVisible();
  await page.getByRole('cell', { name: 'Rs. 1000' }).first().click();
  await expect(page.getByRole('cell', { name: 'Rs. 1000' }).first()).toBeVisible();
  await page.getByRole('cell', { name: 'Rs. 500' }).first().click();
  await expect(page.getByRole('cell', { name: 'Rs. 1000' }).first()).toBeVisible();
});